### ISSUE TITLE
能否提供纯 CSS 文件？

### ISSUE THREAD

**Issue by lucky13820** [Small-Ku/focus-matters#1]
Mac 上有一个 Safari 插件 Cascadea 可以给网站加载自定义 CSS，但是只能加载纯 CSS。不知道能不能提供纯 CSS 文件，这样 Safari 上也可以使用。

**Comment by Small-Ku** [comment]
因為 Stulus 不支援 Firefox Android，而 Firefox Android 跟 iPad Safari 也有類似的情形，所以本來就有打算做。只是最近時間有點緊張，要趕 Assignment，把 Stylus 的選項手工寫成 CSS 的 variable 不容易啊。

**Comment by lucky13820** [comment]
明白，辛苦了。

**Comment by mikefreuden** [comment]
Sorry for the English comment! I'm the developer of Cascadea. This style, and others written in Stylus, should be working in Cascadea 1.5.1 which just released on the App Store. :)

<img width="1757" alt="Screen Shot 2020-04-17 at 12 12 42 PM" src="https://user-images.githubusercontent.com/48981944/79595635-d2ed9980-80a4-11ea-94cf-f90180b01652.png">

**Comment by Small-Ku** [comment]
> Sorry for the English comment! I'm the developer of Cascadea. This style, and others written in Stylus, should be working in Cascadea 1.5.1 which just released on the App Store. :)
> 
> <img alt="Screen Shot 2020-04-17 at 12 12 42 PM" width="1757" src="https://user-images.githubusercontent.com/48981944/79595635-d2ed9980-80a4-11ea-94cf-f90180b01652.png">

Thanks for your works on supporting userstyles in Stylus!
Since Github is a global community, English comments are totally OK.

---

I click the close button accidentally because I am using phone to reply.
BTW, I will provide pure CSS file for other platforms like Firefox Android and iOS Safari.
